export const PURGE_AUTH = "logOut"
export const SET_AUTH = "setUser"
export const SET_BYPASS_SHEETS = "setBypassSheets"
export const SET_BYPASS_SHEETS_SCHEMA = "setBypassSheetsSchema"
export const SET_BYPASS_SHEETS_SCHEMAS = "setBypassSheetsSchemas"
export const SET_CHECKING = "setChecking"
export const SET_ERROR = "setError"
export const SET_ALL_DEPARTMENTS = "setAllDepartments"
export const SET_DEPARTMENTS = "setDepartments"
export const SET_DEPARTMENT = "setDepartment"
export const SET_GROUPS = "setGroups"
export const SET_TOKEN = "setToken"
export const SET_UNREGISTERED_STUDENTS = "setUnregiseredStudents"
export const SET_USERS = "setUsers"

