# Generated by Django 3.1.4 on 2021-01-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.IntegerField()),
                ('direction_of_study', models.CharField(max_length=75)),
                ('institute', models.CharField(max_length=75)),
                ('group', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=75)),
                ('Last_name', models.CharField(max_length=75)),
                ('Midle_name', models.CharField(max_length=75)),
                ('role_in_the_system', models.CharField(max_length=30)),
                ('e_mail', models.EmailField(max_length=254)),
                ('link_on_Administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kemsu_Document.administrator')),
                ('link_on_Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kemsu_Document.employee')),
                ('link_on_Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kemsu_Document.student')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('link_on_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kemsu_Document.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='link_on_Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kemsu_Document.student'),
        ),
    ]
